### ISSUE TITLE
Support for "chrome-extension" in URL_PATTERN_

### ISSUE THREAD

**Issue by comanjoni** [fresheneesz/stackinfo#3]
I'm working on chrome plugin and have found this lib very useful for my needs. Stackinfo is not able to parse callstack inside chrome plugin as it supports only http, https, file and javascript in url.
In my local copy of stackinfo I have added "chrome-extension" in url pattern regular expression and it works.
var URL_PATTERN_ = '((?:http|https|file|chrome-extension)://[^\\s)]+?|javascript:.*)';
It would be good if lib is updated the same way.

**Comment by fresheneesz** [comment]
I would gladly accept a pull request as long as you add a unit test to cover it. Let me know if you have any questions about how to contribute.

**Comment by comanjoni** [comment]
Hi, I have 2 questions:
- Is build working properly? When I run "node build.js" I get "Error: bundle() no longer accepts option arguments." As I figured out browserify have changed boundle method usage and build-modules have not been updated.

**Comment by fresheneesz** [comment]
Hey I noticed you had an issue momentarily with build - I assume you solved it and deleted your comment? I'm curious what the problem was

**Comment by comanjoni** [comment]
Yes, I solved it :)
Well build-modules was crashing because browserify had some updates, so I updated build-modules version to 1.0.12 that supports latest browserify.
On the other side deadunit namespace was changed, actually test method is moved in deadunit (root) object. So I updated calling of test method too.

**Comment by fresheneesz** [comment]
Ah gotcha, good catch. This is why i usually shrinkwrap these things - guess I wasn't doing that yet when i created this module.

**Comment by fresheneesz** [comment]
Merged it in. Thanks!
